POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "bishal@subedi.com",
    "password": "newestpassword"
}
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "bishal",
    "email": "bishal@subedi.com",
    "password": "newestpassword"
}
###
POST http://localhost:3000/auth/verify
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJEb3Zha2lpbjAiLCJlbWFpbCI6ImRvdmFAa2lpbi5jb20iLCJpYXQiOjE2MTI3ODQ5NTh9.ASXvOniXv5VqVqq9JqYwH0pXBi10zcCrKEMeM6VDv5w"
}
###
PUT http://localhost:3000/auth/update/2
Content-Type: application/json

{
    "username": "Dovakiin0._"
}

###
GET http://localhost:3000/test
###
GET http://localhost:3000/auth/2  